aws_bucket_name: www.sam-gibson.co.uk
file_omittance:
  filename: ..\ignore.txt
  omit_files: true
local_repository_path: E:\\Documents\\Repository\\HTML\\www.sam-gibson.co.uk\
logging:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s - %(levelname)s - %(message)s'
  handlers:
    file_handler:
      backupCount: 20
      class: logging.handlers.RotatingFileHandler
      encoding: utf8
      filename: ..\sync.log
      formatter: standard
      level: INFO
      maxBytes: 10485760
  log: true
  loggers:
    <module>:
      handlers:
      - file_handler
      level: INFO
      propagate: false
  root:
    handlers:
    - file_handler
    level: INFO
    propagate: true
  version: 1
