# AWS S3 Settings.
aws_bucket_name: 'mys3bucket'

# Local Repository full file path.
local_repository_path: 'c:\\documents\\mystaticsite\\'

# Omit Files - Files omitted from synchronization, set omit_files to false if you don't require any files omitted.
file_omittance:
    omit_files: true
    filename: 'ignore.txt'

# Logging Configuration - Set log to false if you don't require logging.
logging:
    log: true
    version: 1
    disable_existing_loggers: true
    formatters:
        standard:
            format: "%(asctime)s - %(levelname)s - %(message)s"
    handlers:
        file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: standard
            filename: sync.log
            maxBytes: 10485760 # 10MB
            backupCount: 20
            encoding: utf8
    root:
        level: INFO
        handlers: [file_handler]
        propagate: yes
    loggers:
        <module>:
            level: INFO
            handlers: [file_handler]
            propagate: no